name: Lint and tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v1
      - name: Node.js setup
        uses: actions/setup-node@10.23.2
      - name: installation of dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: E2E tests
        run: npm run pretest:github && npm test
       